### ISSUE TITLE
Information Leakage

### ISSUE THREAD

**Issue by sktgintokii** [ierg4210/shop16#1]
1) Steps:
Visit https://store16.ierg4210.org/account/check/[Payment Id]

2) See:
Transactions of other people

3) Expected:
Not authorized and be redirected

4) Possible fix
Check if username and payment ID match
![store16_1](https://cloud.githubusercontent.com/assets/5036163/7491995/c5bcadf6-f421-11e4-8524-355576bfa039.png)

**Comment by s1155029540** [comment]
Problem Fixed. Thank You.
